/* eslint-disable @next/next/no-css-tags */
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useCallback, useEffect, useState } from "react";
import Menu from "../src/components/layout/Menu";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
    const router = useRouter();
    const [count, setCount] = useState(0);

    useEffect(() => {
        setInterval(() => {
            setCount((prev) => prev + 1);
        }, 100);
    }, []);

    const mainText = "안녕하세요. 개발자 김준한 입니다.";
    const subText = "저는 프론트 개발자이고 리액트를 가장 좋아합니다.";

    useEffect(() => {
        fetch("./api/hello", {}).then((res) => console.log(res));
    }, []);

    return (
        <div className={styles.container}>
            <Menu />
            <Head>
                <title></title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
                <link
                    href="../styles/OpenSans-Regular.ttf"
                    rel="stylesheet"
                    type="text/css"
                />
            </Head>
            <div className={styles.main}>
                <h2 className={styles.mainText}>{mainText.slice(0, count)}</h2>
                <p className={styles.mainText}>
                    {count > 23 && subText.slice(0, count - 23)}
                </p>
            </div>
        </div>
    );
};

export default Home;
