import Head from "next/head";
import React from "react";
import styled from "styled-components";
import Menu from "../src/components/layout/Menu";
import styles from "../styles/intro.module.css";

const Container = styled.div`
    .main {
        width: 100vw;
        height: 100vh;
        background-color: #414242;
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
    }
    p {
        color: white;
        font: 700 normal 2.5em "tahoma";
        text-shadow: 5px 2px #222324, 2px 4px #222324, 3px 5px #222324;
    }
`;

const intro = () => {
    return (
        <Container>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <Menu />
            <div className="main">ㅁㄴㅇㄴㅁㅇㄴㅁ</div>
        </Container>
    );
};

export default intro;
