import Head from "next/head";
import React from "react";
import styles from "../styles/intro.module.css";
const intro = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.main}>ㅁㄴㅇㄴㅁㅇㄴㅁ</div>
    </>
  );
};

export default intro;
